# Generated by Django 5.2.5 on 2025-08-21 16:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='process_monitor.host')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('operating_system', models.CharField(max_length=255)),
                ('processor', models.CharField(max_length=255)),
                ('processor_cores', models.IntegerField()),
                ('processor_threads', models.IntegerField()),
                ('ram_total_gb', models.FloatField()),
                ('ram_used_gb', models.FloatField()),
                ('ram_available_gb', models.FloatField()),
                ('storage_total_gb', models.FloatField()),
                ('storage_used_gb', models.FloatField()),
                ('storage_free_gb', models.FloatField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_snapshots', to='process_monitor.host')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pid', models.IntegerField()),
                ('parent_pid', models.IntegerField(blank=True, null=True)),
                ('cpu_percent', models.FloatField(default=0.0)),
                ('memory_percent', models.FloatField(default=0.0)),
                ('memory_mb', models.FloatField(default=0.0)),
                ('status', models.CharField(default='running', max_length=50)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('command_line', models.TextField(blank=True, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='process_monitor.processsnapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['pid'], name='process_mon_pid_a6107c_idx'), models.Index(fields=['parent_pid'], name='process_mon_parent__48c165_idx'), models.Index(fields=['info'], name='process_mon_info_id_ec56bf_idx')],
            },
        ),
    ]
